Models/CalcUnit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebL_1.Models
{
    public class CalcUnit : ICalcUnit
    {
        public int a { get; set; }
        public int b { get; set; }
        public CalcUnit()
        {
            Random r = new Random();
            a = r.Next(0, 10);
            b = r.Next(0, 10);
        }
        public int Sum() { return a + b; }
        public int Min() { return a - b; }
        public int Mult() { return a * b; }
        public int Div()
        {
            try { return a / b; }
            catch (DivideByZeroException)
            {
                Console.WriteLine("Division by Zero. Operands reversed.");
                //throw ("Division by zero",e);
                return 0;
            }
        }
        
    }

}

Models/CalcUnitManager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebL_1.Models
{
    public class CalcUnitManager : ICalcUnitManager
    {
       
        public ICalcUnit cur { get; set; }
        public ICalcUnit Rebase () {  cur = new CalcUnit(); return cur ; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebL_1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ICalcUnit.cs
namespace WebL_1.Models
{
    public interface ICalcUnit
    {
        int a { get; set; }
        int b { get; set; }

        int Div();
        int Min();
        int Mult();
        int Sum();
       
    }
}

Models/ICalcUnitManager.cs
namespace WebL_1.Models
{
    public interface ICalcUnitManager
    {
        public ICalcUnit cur { get; }
        public ICalcUnit Rebase();
    }
}

Controllers/CalcServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebL_1.Models;

namespace WebL_1.Controllers
{
    public class CalcServiceController : Controller
    {
       
        public string Index()
        {
            return "Meh";
        }

        public IActionResult Model()
        {
            var viewmodel = new CalcUnit();
            return View(viewmodel);
        }

        public IActionResult ServiceInjection()
        {
            ViewData["Title"] = "Service Injection";
            return View();
        }
        public IActionResult VData()
        {
            ViewData["CalcUnit"] = new CalcUnit();
            return View();
        }

        public IActionResult VBag()
        {
            ViewBag.CalcUnit = new CalcUnit();
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebL_1.Models;

namespace WebL_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CalcService/Model.cshtml
@{
    ViewData["Title"] = "ViewModel";
}
@model WebL_1.Models.ICalcUnit
<h2 style="padding-bottom:20px">ViewModel</h2>
 
<h6>Rand Value First: @Model.a </h6>
<h6>Rand Value Second: @Model.b</h6>
<h6>Add: @Model.a + @Model.b = @Model.Sum()</h6>
<h6>Sub: @Model.a - @Model.b = @Model.Min()  </h6>
<h6>Mult: @Model.a * @Model.b = @Model.Mult() </h6>
<h6>Mult: @Model.a / @Model.b = @Model.Div()</h6>

Views/CalcService/ServiceInjection.cshtml
@{
@inject ICalcUnitManager CalcUnitManager;
@CalcUnitManager.Rebase();
}

<h2 style="padding-bottom:20px">@ViewData["Title"]</h2>

<h6>Rand Value First: @CalcUnitManager.cur.a</h6>
<h6>Rand Value Second: @CalcUnitManager.cur.b</h6>
<h6>Add: @CalcUnitManager.cur.a + @CalcUnitManager.cur.b = @CalcUnitManager.cur.Sum()</h6>
<h6>Add: @CalcUnitManager.cur.a - @CalcUnitManager.cur.b = @CalcUnitManager.cur.Min()</h6>
<h6>Add: @CalcUnitManager.cur.a * @CalcUnitManager.cur.b = @CalcUnitManager.cur.Mult()</h6>
<h6>Add: @CalcUnitManager.cur.a / @CalcUnitManager.cur.b = @CalcUnitManager.cur.Div()</h6>

Views/CalcService/VBag.cshtml
@{
    ViewBag.Title = "ViewBag";
}


<h2 style="padding-bottom:20px">@ViewBag.Title</h2>

<h6>Rand Value First: @ViewBag.CalcUnit.a</h6>
<h6>Rand Value Second: @ViewBag.CalcUnit.b</h6>
<h6>Add: @ViewBag.CalcUnit.a + @ViewBag.CalcUnit.b = @ViewBag.CalcUnit.Sum()</h6>
<h6>Add: @ViewBag.CalcUnit.a - @ViewBag.CalcUnit.b = @ViewBag.CalcUnit.Min()</h6>
<h6>Add: @ViewBag.CalcUnit.a * @ViewBag.CalcUnit.b = @ViewBag.CalcUnit.Mult()</h6>
<h6>Add: @ViewBag.CalcUnit.a / @ViewBag.CalcUnit.b = @ViewBag.CalcUnit.Div()</h6>

Views/CalcService/VData.cshtml
@{
    ViewData["Title"] = "ViewData";
var res = ViewData["CalcUnit"] as ICalcUnit;
}


@{
    ViewData["Title"] = "ViewData";
}
<h2 style="padding-bottom:20px">@ViewData["Title"]</h2>

<h6>Rand Value First: @res.a</h6>
<h6>Rand Value Second: @res.b</h6>
<h6>Add: @res.a + @res.b = @res.Sum()</h6>
<h6>Add: @res.a - @res.b = @res.Min()</h6>
<h6>Add: @res.a * @res.b = @res.Mult()</h6>
<h6>Add: @res.a / @res.b = @res.Div()</h6>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div style=" text-align:left">
    <h5 class="display-4"style="padding-bottom:20px">Calc Service Demonstration</h5>
    <ul>
        <li><a asp-controller="CalcService" asp-action="Model">Using ViewModel Calc</a></li>
        <li><a asp-controller="CalcService" asp-action="Vdata">Using ViewData Calc</a></li>
        <li><a asp-controller="CalcService" asp-action="VBag">Using ViewBag Calc</a></li>
        <li><a asp-controller="CalcService" asp-action="ServiceInjection">Using Service Injection</a></li>

    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Backend1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Backend1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>